### ISSUE TITLE
Unable to upload

### ISSUE THREAD

**Issue by cliff-wakefield-acurus** [aws-cloudformation/aws-cloudformation-resource-providers-wafv2#16]
When it comes to submitting the resource I get the following error from `cfn submit -vv --set-default`

`botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the RegisterType operation: Type name AWS::WAFv2::LoggingConfiguration is using a restricted namespace aws`

**Comment by advaj** [comment]
Hey - thanks for the feedback. The resource naming has been made stricter with the release of the latest Public Registry. I have created a Private Resource and uploaded it [here](https://github.com/advaj/private-wafv2-loggingconfiguration) - there is no change in the functionality, just that the name of the resource has now been made: Private::WAFv2::LoggingConfiguration. Do let me know if you are able to deploy this successfully.

**Comment by wolfeidau** [comment]
@advaj can we publish it in the public registry? 

Would love to road test this!

**Comment by advaj** [comment]
Hey - thank you for your interest! I am not aware of the roadmap for this particular resource. But if/when this resource becomes public, the functionality and behavior will be similar to my implementation. I noticed that there were a lot of requests for this resource and decided to write a private resource so folks in the community can benefit. 

Do let me know if you need help in setting this up or if you have any other suggestions for this resource and I would be glad to help out!

**Comment by jerechenamz** [comment]
Closing as LoggingConfiguration is now public
